Repository akhil-aggarwal/cookie, pull requests merged in 2022-10, with the labels that each got.

#16 Updated README file
  README.md
Labels: documentation, enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#23 Updated About Page
  about.html
  assets/css/material-kit.css
  index.html
  style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#25 Update README.md
  README.md
Labels: documentation, enhancement, hacktoberfest, hacktoberfest-accepted

#30 fix: form now submits if you press enter
  index.html
  script.js
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#39 Done changes as mentioned in issue #31
  .vscode/settings.json
  about.html
  index.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#41 updating path #40
  script.js
Labels: bug, enhancement, hacktoberfest, hacktoberfest-accepted

#42 Added reload
  node_modules/.package-lock.json
  package-lock.json
  script.js
Labels: bug, enhancement, hacktoberfest, hacktoberfest-accepted

#44 Adding favicons
  assets/favicons/favicon.ico
  assets/favicons/favicon1.ico
  index.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#50 making scroll-behavior smooth
  style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#59 Changed Issue Templates for ease & better UI
  .github/ISSUE_TEMPLATE/Bug_Report.yml
  .github/ISSUE_TEMPLATE/Feature_Request.yml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation, enhancement, hacktoberfest, hacktoberfest-accepted

#57 Contributors Page
  about.html
  contributor.html
  contributor.js
  index.html
  style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#65 Added Driving License Button
  index.html
  script.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#72 make more attractive
  about.html
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#71 orange button option added
  about.html
  assets/css/material-kit_orange.min.css
  contributor.html
  index.html
  script.js
  style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#78 Update as mentioned in Issue
  contributor.html
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted
